# Generated by Django 2.2.8 on 2020-07-08 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200701_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='dateCompleted',
            new_name='datecompleted',
        ),
    ]
